- app/makefile
Makefile: redirect makeflags to sub-makefiles
> Makefile: redirect makeflags to sub-makefiles

- RTKLib.pro
- app/rtknavi_qt/navimain.cpp
- app/rtknavi_qt/navimain.h
- app/rtkplot_qt/plotcmn.cpp
- app/strsvr_qt/svrmain.cpp
- src/rtklib.h
- src/solution.c
- src/streamsvr.c
```
mkdir build
cd build
qmake ..
make -j4
```
> Compile all QT GUIs

- RTKLib.pro
- app/app.pro
- app/rtkconv_qt/convmain.cpp
- app/rtkconv_qt/rtkconv_qt.pro
- app/rtkget_qt/getmain.cpp
- app/rtkget_qt/rtkget_qt.pro
- app/rtknavi_qt/navimain.cpp
- app/rtknavi_qt/navimain.h
- app/rtknavi_qt/rtknavi_qt.pro
- app/rtkplot_qt/plotcmn.cpp
- app/rtkplot_qt/plotdata.cpp
- app/rtkplot_qt/plotmain.cpp
- app/rtkplot_qt/rtkplot_qt.pro
- app/rtkpost_qt/postmain.cpp
- app/rtkpost_qt/rtkpost_qt.pro
- app/srctblbrows_qt/srctblbrows_qt.pro
- app/strsvr_qt/strsvr_qt.pro
- app/strsvr_qt/svrmain.cpp
- bin/readme.txt
- src/rtklib.h
- src/solution.c
- src/src.pro
- src/streamsvr.c
tested with qt 5.7.1 and qtcreator on:
osx 10.11.6 
ubuntu 16.04.4
raspbian stretch
windows 7
will be working on some tutorials on how to compile soon.
> updated to compile and run with qtcreator across osx, linux, and windows

- src/geoid.c
- src/rtklib.h
- src/stream.c
Reverts rtklibexplorer/RTKLIB#26.  Creates build errors in windows
> Revert "Unixsocket streams and french RAF09 geoid"

- src/solution.c
Similar to c00f971af1005d41cd735dcc8507bbf6691dc9e2
> Output velocity for enu

- app/qtapp/rtkconv_qt/convopt.ui
In convopt.ui, changed approx pos XYZ min/max values from [0,1000000] to [-9000000,9000000]
> RTKConv options UI : fix approx pos XYZ min/max values

- app/consapp/str2str/str2str.c
- app/winapp/rtknavi/navimain.cpp
window app config, AR thread min, max read bug fixed
> winapp config item bug fix

- src/ppp.c
The caller is not always using these outputs and this is a slight performance improvement.
> ppp_res: accept output pointers v, H, and R as NULL

- src/ppp.c
ppp_res() was applying a slant factor to the iono delays that already included the application of a slant factor, and this caused the delays to be too great as the zenith angle increased.
> ppp: avoid applying an iono slant factor twice.

- src/rtkpos.c
Misc code improvement split out from https://github.com/rtklibexplorer/RTKLIB/pull/197 credit to @jwidauer
These misc code changes can become frustrating noise when exploring larger changes to these areas of the code, so just suggesting merging these first.
> holdamb: remove unused summation.

- src/rtkpos.c
Misc code improvement split out from https://github.com/rtklibexplorer/RTKLIB/pull/197 credit to @jwidauer
> ddres: remove unused nav argument

- src/postpos.c
rtkinit() was being called twice for a combined forward and backward solution without calling rtkclose() twice, leading to memory loss.
Rework the code to call rtkinit() and rtkclose() from execses() where the pairing of these calls is more obvious.
> postproc rtkinit: avoid duplicate rtkinit without rtkfree

- app/qtapp/rtknavi_qt/navimain.cpp
Reverts rtklibexplorer/RTKLIB#273 --> not my branch
> Revert "rtknavi_qt serverStart: initialize cmd strings emptry"

- src/options.c
This was indexing before the comment string, when the value was a digit that matched the first comment digit, and it potentially got worse.
> str2enum: rewrite to avoid indexing outside the strings

- src/solution.c
The code builds a list of satellites to emit, at most 12, and a count, but was not respecting the count when emitting them leading to undefined behaviour.
Also correct the indentation around this fix.
> outnmea_gsa: respect the count of satellites to emit

- app/consapp/convbin/gcc/makefile
- app/consapp/pos2kml/gcc/makefile
- app/consapp/rnx2rtkp/gcc/makefile
- app/consapp/rtkrcv/gcc/makefile
- app/consapp/str2str/gcc/makefile
This enables compilation on macOS
> Remove links to librt

- src/solution.c
Two of the paths were blindly adding a separator length and could jump the end of the string if it was short. The caller could attempt to decode garbage beyond the end of the string.
The third path was not advancing over the time if there was no trailing separator and was returning success in this case. The caller could attempt to decode part of the time as other data, but would surely fail gracefully.
Have these paths search for the trailing separator and return NULL if not found, and if found then accurately return a pointer to the end of this separator.
> decode_soltime: better handle the trailing separator

- app/consapp/rnx2rtkp/rnx2rtkp.c
- app/qtapp/rtknavi_qt/naviopt.cpp
- app/qtapp/rtkplot_qt/plotdata.cpp
- app/qtapp/rtkplot_qt/plotmain.cpp
- app/qtapp/rtkpost_qt/postmain.cpp
- app/qtapp/rtkpost_qt/postopt.cpp
- app/winapp/rtknavi/naviopt.cpp
- app/winapp/rtkplot/plotdata.cpp
- app/winapp/rtkplot/plotmain.cpp
- app/winapp/rtkpost/postmain.cpp
- app/winapp/rtkpost/postopt.cpp
Noticed some opportunities to use the defined symbols rather than numeric values. Submitting in case this of interest, it does not fix anything.
> misc use of defined symbols over numeric constants

- app/qtapp/appcmn_qt/navi_post_opt.ui
There is no logic to enabled this otherwise.
> qt gui solution format: enable by default

- app/qtapp/rtknavi_qt/navimain.cpp
otype[] has six element, but the code was incorrectly looping over only five elements, which is corrected, and this broke some output type settings such as a file type would default to a serial type (index 0). Rewrite to make this clearer.
Guard the use of the streamType[], defaulting to disabled if out of range. Seen some out of range values being presented in streamType[].
> Qt gui showOptionsDialog: correct the iteration limits, rework

- src/convrnx.c
- src/rcvraw.c
> trace formats: correct missing arguments

- app/qtapp/appcmn_qt/navi_post_opt.cpp
> Qt gui option saveClose: zero fill pcv0

- app/qtapp/rtknavi_qt/mondlg.cpp
Rework the guarding of the nav eph. The indexing here needs to multiply the offset by the number of sats, see rtksvr.c update_eph(). Also use the nav eph number of element to guard the offset index and fill with a zero eph if oob. The demo5 code has moved to index per sat and then by the offset, and has a per sat number of elements, but the code is similiar.
The width elements were short in setNavigation() and setSat() causing OOB access. Just add the extra entries for now but the cause might need review.
In showRtcmSsr(), slightly rework an iteration over the code indexes to avoid CODE_NONE, although it was not broken and code2obs() does catch an OOB code index.
> Qt gui monitor: nav empty guard, widths, rtcm ssr

- app/qtapp/appcmn_qt/refdlg.cpp
- app/qtapp/qtapp.pri
- app/qtapp/rtknavi_qt/markdlg.cpp
- app/qtapp/rtknavi_qt/markdlg.ui
- app/qtapp/rtknavi_qt/navimain.cpp
- src/src.pro
> Qt Changes

- app/qtapp/appcmn_qt/navi_post_opt.cpp
- app/qtapp/appcmn_qt/navi_post_opt.h
- app/qtapp/rtkconv_qt/convmain.cpp
- app/qtapp/rtkconv_qt/convmain.h
- app/qtapp/rtknavi_qt/mondlg.cpp
- app/qtapp/rtknavi_qt/mondlg.h
- app/qtapp/rtknavi_qt/mondlg.ui
- app/qtapp/rtknavi_qt/navimain.cpp
- **Set processing options even when options dialog for rtknavi_qt and rtkpost_qt is never execuate**
- **Update rtknavi_qt monitor dialog**
- **Rtkconv_qt updates - fix showing process - update output path instantly while typing**
- **Fixes to rtknavi_qt**
> Qt Gui Changes

- src/stream.c
A minor nit in the ntrip stream code. This would not appear to be capable of causing corruption, just some loss of received content at the start of the stream, and might not have been reachable.
For the ntrip stream, initial content is read into the response buffer for processing, but once processed there can be some content remaining that can be general input from this stream. The code was using the most recent number of requested bytes and discarding the reset. Typically the caller was reading into a large buffer so requesting more than buffered and so all the content was consumed. Update the code to also consume all the buffer content even if the caller is using a small buffer. Also expand the two cases to make the code clearer.
Rework reqntrip_c() and rspntrip_s() a little, to use …
> stream readntrip: correct reading from the response buffer

- app/qtapp/rtknavi_qt/mondlg.cpp
Was indexing into the rows using the state index but this is not equivalent when cBSelectSatellites is set and likely indexes beyond the reduced set of rows.
Also remove redundant setting of the row count.
> rtknavi_qt mon showEstimates: correct row index

- app/qtapp/rtknavi_qt/mondlg.cpp
to prevent excessive abbreviation.
> rtknavi_qt mon: increase some column widths

- app/qtapp/rtknavi_qt/mondlg.cpp
to match the output in showSat().
> rtknavi_qt mon setSat: correct the column count and headings

- app/qtapp/appcmn_qt/tcpoptdlg.cpp
- app/qtapp/appcmn_qt/tspandlg.cpp
- app/qtapp/rtkconv_qt/convmain.cpp
- app/qtapp/rtklaunch_qt/launchmain.cpp
- app/qtapp/rtknavi_qt/navimain.cpp
- app/qtapp/rtkplot_qt/plotdata.cpp
- app/qtapp/rtkpost_qt/kmzconv.cpp
- app/qtapp/rtkpost_qt/postmain.cpp
- src/rcv/septentrio.c
- **Septentrio receiver support**
- **Qt Gui compile fix**
- **Qt GUI Update better call external apps**
> Qt Gui Updates

- app/qtapp/appcmn_qt/tspandlg.cpp
- make Timespan Dialog compile with Qt5
> Qt Gui: Timespan Dialog

- app/qtapp/appcmn_qt/navi_post_opt.cpp
- **Qt Gui Fix**
- **Qt Gui Fixes**
- **Qt Gui Fix**
- **Qt Gui Update (rtkpost_qt)**
- **Qt Gui: rtnavi_qt/rtkpost_qt options dialog**
> Qt Gui Update II

- app/consapp/rtkrcv/rtkrcv.c
The library and gui apps already support these receiver options.
> rtkrcv: add support for receiver options

- src/rcv/septentrio.c
Took another look at the call to decode_frame and calling  decode_frame() for the eph after subframe 3 seems appropriate as that looks at subframes 1,2 and 3.
* call decode_frame() for the eph after subframe 3.
* for subframes 4 and 5, clear the respective subframe after decoding, rather than the prior frame.
* for sigPriority() accept an extended index in the default path, to avoid dropping some signals
* decode_gpsionutc() should return 9
* misc spelling
> septentrio: decode_gpsrawcnav decode_frame fix

- app/qtapp/rtkplot_qt/plotmain.cpp
Obs: *.*O *O.rnx *O.rnx.gz *O.crx *O.crx.gz
Nav: *N.rnx.gz
> rtkplot_qt: recognize more common obs and nav files patterns

- src/rcv/septentrio.c
- src/rcvraw.c
- src/rtklib.h
Allowing multiple sbf streams to be decoded simultaneously.
> septentrio: move the static data into the raw structure

- src/rcv/septentrio.c
otherwise the caller will not recognise that data has been added.
Noted on a meas3 dataset without epoch end blocks which was losing data.
> septentrio: pass on the flushobuf return value

- src/rcv/septentrio.c
With https://github.com/rtklibexplorer/RTKLIB/pull/456 the organisation, agency, and marker type can be passed through too, commented out for now. Do get the receiver number, type and version, which might be useful.
> septentrio: implement the rx setup block

- app/consapp/convbin/convbin.c
adding the --glofcn command line argument. The GUI convbin app already has this support.
> convbin: add GLONASS fcn initialization support

- app/qtapp/appcmn_qt/freqdlg.ui
- app/qtapp/rtkconv_qt/codeopt.cpp
- app/qtapp/rtkconv_qt/codeopt.ui
- app/qtapp/rtkconv_qt/convopt.cpp
The mask length needed to be increased with the addition of the two new codes.
Add support for BDS L3A and NavIC L1.
> rtkconv_qt: increase mask length, support new codes

- app/qtapp/rtkconv_qt/codeopt.cpp
- app/qtapp/rtkconv_qt/codeopt.ui
Missed QZSS 1E in the last attempt.
> rtkconv_qt: add signals QZSS 1E

- src/sbas.c
> sbas: fix comment typo

- app/qtapp/rtknavi_qt/mondlg.cpp
> rtknavi_qt: increase monitor column width for sbas and rtcm

- app/qtapp/rtknavi_qt/mondlg.cpp
- app/qtapp/rtknavi_qt/mondlg.h
Update the F/Nav vs I/Nav info display when the set changes.
> rknavi_qt monitor galileo nav: update info on set change

- app/winapp/rtknavi/naviopt.cpp
comma typo, fix for one of my prior patches.
> win rtknavi: correct SOLOPT

- app/winapp/rtknavi/naviopt.cpp
spotted another place to use a define over a baked in constant.
> win rtknavi: defines over baked in constants

- src/postpos.c
Reverts rtklibexplorer/RTKLIB#253
Merge was unintentional
> Revert "postpos inputobs: guard against iobsr being out of range"

- app/qtapp/rtkplot_qt/plotmain.cpp
- app/qtapp/rtkplot_qt/plotopt.ui
Perhaps viewing smaller differences is of general interest.
> rtkplot_qt: add some finer scaling options

- src/rinex.c
https://github.com/rtklibexplorer/RTKLIB/issues/568
> rinex: canonicalize to IGS antenna format

- app/consapp/rtkrcv/rtkrcv.c
Noticed the unicore format was missing, might as well add it here too.
> rtkrcv: add unicore as a format option

- app/consapp/str2str/str2str.c
Use the current messages for each -out option, so the -msg option now needs to precede the -out option, and each output stream can have a separate set of messages.
> str2str: messages per output stream

- src/rtkpos.c
Take care not to index into the phase biases when in DGPS mode as there are no phase biases in this mode.
> rtkpos: DGPS mode fixes

- app/qtapp/rtkplot_qt/plotdraw.cpp
- app/qtapp/rtkplot_qt/plotmain.cpp
The following improvements have been made to the Qt version of RTKPLOT
- Fixed UI blurring on high resolution displays.
- Fixed a bug that prevented drag-and-drop files from being loaded.
> RTKPlot Qt: Improve high-DPI support & fix drag-and-drop bug

- src/rtkpos.c
saw an overflow here, so increase the buffer size a little.
> rtkpos errmsg: increase buffer to 384

- app/qtapp/rtkplot_qt/plotopt.ui
fwiw, helps at times when seeing 30 to 40 satellites
> rtkplot_qt: add DOP/NSAT range of 40

- app/qtapp/rtknavi_qt/mondlg.cpp
rather than repeating its definition.
> rtknavi-qt: use NSATSBS

- src/sofa.c
> sofa: quieten some compiler warnings

- src/rinex.c
cleans up some redundant tests - from my prior addition of this function.
> rinex igsanttype: avoid redundant tests

- src/rtkcmn.c
to address reported performance issues using the sofa version. This keeps the sofa version code in place as a compilation option for now.
Shall look into the performance issue further.
> sunmoonpos: revert to the prior rtklib version

- .gitignore
- app/qtapp/appcmn_qt/fileoptdlg.cpp
- app/qtapp/appcmn_qt/navi_post_opt.cpp
- app/qtapp/appcmn_qt/navi_post_opt.ui
- app/qtapp/rtknavi_qt/instrdlg.cpp
- app/qtapp/rtknavi_qt/logstrdlg.cpp
- app/qtapp/rtknavi_qt/mondlg.cpp
- app/qtapp/rtknavi_qt/outstrdlg.cpp
- app/qtapp/rtkplot_qt/plotmain.cpp
- app/qtapp/strsvr_qt/svrmain.cpp
- app/qtapp/strsvr_qt/svrmain.ui
- app/qtapp/strsvr_qt/svroptdlg.ui
logging of input and output streams is fixed, 
placeholder text for receiver configuration corrected, 
default height of GUIs is reduced
fix misplaced tooltip for used GNSSs
> Some fixes for strsvr_qt app

- src/stream.c
This is a suggestion to address the matter of the error number identified in the following:
https://github.com/rtklibexplorer/RTKLIB/issues/166
https://github.com/rtklibexplorer/RTKLIB/issues/575
Have recv_nb() send_nb() connect_nb() accept_nb() return the error number rather than having the caller access the error number by calling errsock().
There were cases in which the caller was relying on the error number when it had not been set by these functions. For example when recv_nb() returns -1 with and error number of zero for a disconnect.
Having these function return the error number allows the caller to rely on it and encapsulates the system differences into these functions.
> stream: rework low level function to return the error number

- app/qtapp/rtkconv_qt/codeopt.cpp
- app/qtapp/rtkconv_qt/codeopt.ui
which was incorrectly referring to 6S.
> rtkconv_qt code options: fix BDS 6Z

- src/rtksvr.c
Function rtksvrmark() was acquiring the rtksvr lock and then calling saveoutbuf() which attempted to recursively acquire the lock leading to a lockup. Move the locking out of saveoutbuf() for the caller to manage.
> rtksvrmark: avoid a recursive lock attempt on saveoutbuf

- app/consapp/rtkrcv/rtkrcv.c
If only to test this code path.
> rtkrcv: add a 'mark' command to log a marker

- src/rinex.c
- src/rtkcmn.c
- src/rtklib.h
This can be useful reading some of the fixed format files beyond the RINEX format. Have a few other pending uses for this.
> Setstr export

- app/winapp/rtkconv/convmain.cpp
- app/winapp/rtkconv/convmain.h
- app/winapp/rtkconv/convopt.cpp
- app/winapp/rtkconv/convopt.dfm
- app/winapp/rtkconv/convopt.h
> rtkconv: add sort satellites option

- app/winapp/rtknavi/markdlg.cpp
this data is not used, but might as well correct the code.
> rtknavi: fix initialization

- app/winapp/srctblbrows/browsmain.cpp
The loop was not checking the result of strtok, typo.
Convert strtok usage to strtok_r for thread safety.
> winapp srctblbrowser UpdateCaster: correct parsing

- app/qtapp/rtkplot_qt/plotdata.cpp
- app/winapp/rtkplot/plotdata.cpp
> rtkplot/rtkplot_qt: calculate multipath even if either L1 or L2 is not

- app/qtapp/rtkplot_qt/plotdata.cpp
- app/winapp/rtkplot/plotdata.cpp
some possible uses of unused variables. Initialize freq1 and freq2 to zero.
> apps update-mp: rework to quieten comp. warnings

- readme.txt
https://github.com/rtklibexplorer/RTKLIB/issues/731
> Note CRX2RNX in the readme.

- app/consapp/str2str/str2str.c
https://github.com/rtklibexplorer/RTKLIB/issues/751
> str2str usage: add an example -msg option before an -out argument
