rtklibexplorer/RTKLIB

src/options.c, src/pntpos.c, src/ppp.c, src/rtkcmn.c, src/rtklib.h, src/rtkpos.c, src/solution.c
* Well-known SNR error variance weighting scheme incorporated into RTKLIB code. The choice of the alternative scheme may affect a result.
phase error variance == SQR(errphase) * 10 ^ ( 0.1 * (snr_max - snr) ) 
* Fix: iono-free error variance scale factor for RTK changed from 3.0 to SQR(3.0)
'stats' group of options is as follows:
stats-weightmode  =snr      # (0:elevation,1:snr)   # new option
stats-eratio1           =300
stats-eratio2           =300
stats-errphase        =0.003   # (m)
stats-errphaseel     =0.003   # (m)
stats-errphasebl     =0          # (m/10km)
stats-errdoppler     =1          # (Hz)
stats-snrmax           =52       # (dB.Hz)                    # new option
=> SNR weighting option added to CUI version for SPP, PPP and RTK

app/convbin/gcc/makefile, app/pos2kml/gcc/makefile, app/rnx2rtkp/gcc/makefile, app/rtkrcv/gcc/makefile, app/str2str/gcc/makefile
-lrt is not needed on OS X & will fail when building.  Adding to check if system is OS X.
=> modify makefiles for cli apps to build on OS X

src/geoid.c, src/rtklib.h, src/stream.c
This is a pull request containing 2 commits since I move from original RTKLIB to rtklibexplorer/demo5:
1- (08ec534) is the addition of a new stream type "unix socket" as stream number 15 in rtklib.h, this is required for embedding rtklib in android , communication between java and native is done with unix sockets rather than udp or tcp. This is use for many years in my RtkGps android app ( https://play.google.com/store/apps/details?id=gpsplus.rtkgps )
2- (5307674) is the support for native french RAF09 geoid in geoid.c, it has been long discussed and tested with Tomaji Takasu. RAF09 is the legal geoid in France it was released as public domain and can be find here on french administration site: http://geodesie.ign.fr/contenu/fichiers/documentation/grilles/metropole/RAF09.mnt
=> Unixsocket streams and french RAF09 geoid

src/rtkpos.c
In this PR, I add the sign of the time delta `tt` to flip the accel direction depending on the forward/backward modes.
The time evolution of kalman-filter in the backward mode is calculated by using the `udpos` function with the reversed time delta `tt` to flip the direction of the velocity.
But the accel terms are given by `SQRT(tt)/2`, which always returns positive values. This seems that the accel terms in the backward mode shift the resulting position to the opposite side.
So I think the sign of the time delta is needed for the accel term.
I'm not familiar with the rtklib code so I might be wrong, but I appreciate it if you review this.
=> Fix to take into account the direction of accel term

app/qtapp/rtkget_qt/getmain.cpp, app/qtapp/rtkplot_qt/plotmain.cpp, app/qtapp/rtkpost_qt/postmain.cpp
This should fix #144.
There are some API's difference between Qt5 and Qt6. Commit f04f12728 added support for Qt6 but broke Qt5.
=> Fix QtApp when using Qt 5 issue #144

src/rtklib.h
Building RTKLIB as a shared library on Windows fails otherwise.
This cropped up when adding RTKLIB as a package for the Conan package manager:
* https://github.com/conan-io/conan-center-index/pull/17998
I created an identical PR upstream as well: https://github.com/tomojitakasu/RTKLIB/pull/727
=> Add missing EXPORT to global variables

src/rcv/ublox.c
This is encoded as 0.01*2^n, but the decoding was being applied twice, once in ublox.c:decode_rxmrawx() and then again when used in rtkpos.c etc.
Also extend the encoding in the rinex files to include the full range 0-15, encoded as a hex digit.
=> ublox: correct the encoding of the carrier phase std

src/preceph.c
Move the call to init_bias_ix() into readdcb() so that this table is also initialized when reading only DCB files, otherwise this table is uninitialized and the biases are usable in some paths.
=> Initialize the bias index table when reading DCB files too.

app/consapp/convbin/convbin.c, app/qtapp/appcmn_qt/tspandlg.cpp, app/qtapp/rtkget_qt/getmain.h, app/qtapp/rtkplot_qt/mapoptdlg.cpp, app/qtapp/rtkplot_qt/plotdraw.cpp, app/qtapp/rtkplot_qt/plotmain.h, app/qtapp/rtkplot_qt/vmapdlg.cpp, src/download.c, src/options.c, src/rinex.c, src/rtkcmn.c, src/rtklib.h, src/stream.c
Hi there!
While using rtklib for a project, I discovered these two small defects and fixed them:
1. While converting string options to an enum, it was possible to read out of bounds data, when iterating backwards through the comments.
2. The definitions for the different `lock...` methods and classes conflicted with definitions in the stdcpp library and / or some Qt libraries. I fixed this by renaming the defines to have an `rtklib_` prefix, to hopefully prevent this in the future.
I've also been working on improving the runtime performance of rtklib and was wondering whether these changes might also be of interested. I'll open a separate PR for some initial improvements and we can discuss there.
=> Fix buffer overflow while parsing options and rename defines to not conflict with definitions from other projects

src/pntpos.c, src/rtkpos.c
And enable output of the IRN-GPS and QZS-GPS time offsets in the stat file CLK entries.
=> pntpos: enable QZS-GPS time offset

src/rtkcmn.c
Account for the receiver hight, so that this function now returns the same result as ionmapf().
=> ionppp: account for the receiver hight

app/consapp/convbin/convbin.c, src/convgpx.c, src/rcv/rt17.c, src/rcv/ublox.c, src/rtkcmn.c, src/rtksvr.c, src/src.pro, src/stream.c
Spaces give more consistent spacing and indentation than tabs across editors which might interpret tabs as 4 or 8 spaces, and many of the upstream files use spaces rather than tabs for indentation, so here is a suggestion to replace some of the sparse instances of tabs with spaces. Some code files use largely tabs and these are not patched to spaces here.
=> Replace some tabs with spaces.

src/pntpos.c
Fix memory corruption with QZSDT enabled and only one system configured.
rescode() can include up to (NX-3) extra constraints, and estpos() needs to allocate memory for all of these in the worst case, and was allocating an extra 4 rows but needs 5 extra rows with QZSDT enabled. Allocate an extra (NX-3) so that this handles more constraints being added in future, handles an increase in NX.
=> estpos: correct array allocations with QZSDT enabled

src/ephemeris.c, src/pntpos.c, src/ppp.c, src/preceph.c, src/rtkcmn.c, src/rtklib.h, src/tides.c, util/testeph/diffeph.c
As discussed in #191, this is a separate PR for adding the specializations of the dot product methods.
=> Add specialized dot product methods for vectors of size two and three

src/trace.h
Need this to link with c++ apps, such as the qt apps.
Might this also correct issues with trace.h that required it to be copied to rtklib.h?
=> trace.h: work with c++

src/rtkpos.c
`k` can be larger than `rtk->nx`, causing invalid memory access and incorrect output values to be printed.
=> Fix out-of-bounds error in outsolstat()

src/ppp.c, src/rtkpos.c
Noted that initx() was surprisingly hot in ppp, and that moving the conditional out of the loop and inlining improved performance slightly.
=> initx: rework loops for performance and inline

src/rtkcmn.c
Use strtod() rather than sscanf(). Plus a few other code changes to assist the compiler to produce better code.
=> str2num: improve performance

src/lambda.c, src/pntpos.c, src/ppp.c, src/rtkcmn.c, src/rtklib.h, src/rtkpos.c, src/tides.c, src/tle.c
Reorder the loop iteration over the arrays to prioritise sequential linear access patterns, attempting to improving data cache efficiency.
Hoist the test for the special case of beta being zero out of the loops. This is a necessary special case, not just for performance optimization as it avoids reading from the C array.
Add a further special case for both beta and alpha being zero. This is just a performance optimization. This case occurs in some very hot code so it makes a further small improvement.
Inspired by https://github.com/rtklibexplorer/RTKLIB/pull/197 credit to @jwidauer
There are a few special cases that are very hot code, and noted in particular the following which account for most of
the time in matmul(). So it helps to optimize these by hoisting the tests and adding a …
=> matmu: improve cache data access patterns and hoist tests.

src/convrnx.c
The case in which a station antenna xyz delta fails to be set due to a lack of a station position was not be handled, and in outrnxevent() was leading to the use of uninitialized data.
Also omit a redundant checkout for the station antenna delta.
Noted a compiler warning here, and there does appear to be a path in which uninitialized data might be used. Not sure of the appropriate handling in this case but it does appear to be an error path so have it emit a trace warning and in setopt_sta() not update the options and in outrnxevent() default to a delta of zero even ignoring a station height.
=> convrnx: antenna xyz delta handling due to no position

src/rinex.c
Signal-in-Space Accuracy (SISA) values over 0.49 fall into the next brack up, not values over 0.50. Similarly for other ranges.
Round to an integer index, rather than truncating.
=> SISA: round to integer, and correct ranges

src/ephemeris.c
Rare if not typically impossible case in which uninitialized data is used.
Continue to use the iterative solution in the exceptional case of an iteration overflow, rather than returning with uninitialized function outputs.
In this exceptional case, the solution is likely as good as can be with the numerical precision.
The current return path was not setting the function outputs on that return path and the callers may be using uninitialized data in this case.
=> kepler: continue on an iteration overflow

src/ephemeris.c
Return 0, an error, in the case that a fallback call to ephpos() returns an error, rather than returning success in this case.
Btw find it a little hard to follow the logic here with the satellite health return value svh, but have not touched that assuming that if a correction is not expected then not to mark the result as uncorrected, not to set svh to -1?
=> satpos_sbas: check the return value of ephpos()

src/gis.c
Was using sizeof gis_poly_t which is at present the same size.
=> gis read_polygon: correct malloc sizeof gis_polygon_t

src/download.c
Move the call to showmsg() after local[] has been initialized.
Untested, but there does appear to be an issue here.
=> download test_local: correct undefined use of local[]

src/ionex.c
readtec was initializing the header values, lats[], lons[] etc once before reading all files, and readionexh() fills in only those fields that it finds, so the header values from one file might have lingered when reading the body of later files which does not appear intended.
Would it be expected to have header values from a prior file linger as defaults for the next? Perhaps this is an issue.
=> ionex readtec: reinit header values for each file

src/rcv/ublox.c
Spotted a test in decode_rxmrawx() that would appear to fail it's purpose. The code below:
```
/* set cycle slip if half cycle subtract bit changed state */
LLI|=halfc!=raw->halfc[sat-1][idx]?LLI_SLIP:0;
```
as `raw->halfc[sat-1][idx]=halfc` is above this test so the test will always fail.
Have not tested at all what effect this extra slip detection test might have on results, if it should be enabled with this fix. and this PR is more of a pointer to an issue for ublox decoder.
The half cycle subtract bit state change detection was broken because the state in raw->halfc was updated before comparing it to the new value. Move the update of raw->halfc after this test.
=> ublox rxmrawx: detection of half cycle subtract bit state change

src/sbas.c
No expert in this area, but there appears a possibility of an oob read from iodf[] that might be best guarded against. See also https://github.com/tomojitakasu/RTKLIB/issues/747
Just guarding indexing into iodf[] in decode_sbstype6() rather than limiting sbssat->nsat in decode_sbstype1().
Seems to concur with Annex 10 3.5.4.1 of the Convention on International Civil Aviation "The [PRN] mask shall set up to 51 of the 210 PRN mask values"
=> sbas decode_sbstype6: avoid oob read from iodf[]

src/stream.c
The non-WIN32 path was always returning 0 indicating an error.
Further it was flagging an error if not all the buffer was written.
The serial connection is opened non-blocking. So the write can return less than the full amount requested. This function appears intended to be non-blocking, so in this case return the amount written rather than flagging an error.
This is not a complete fix which might be more extensive. The write can also return zero which is not necessarily an error, and it might also return -1 and set errno to EAGAIN if it would have blocked.
=> stream writeserial: patch writes for non-WIN32 platforms

app/winapp/rtkget/getmain.cpp, app/winapp/rtkplot/plotdata.cpp, app/winapp/rtkplot/plotmain.cpp, src/postpos.c, src/preceph.c, src/rtkcmn.c, src/solution.c, src/stream.c, src/tle.c
Include a maximum width on scanf string input, to avoid an overflow of the target string buffer.
Also initialized scanf optional values, for the case in which they are not supplied.
=> scanf string maximum widths

src/rtksvr.c
In the case of a download file to decode, fobs[] was not being set and it was not cleared on each iteration cycle, and this would appear to lead to potential unintended behavior.
=> rtksvr rtksvrthread: reset fobs[] on each iteration

src/rtkpos.c
The baseline is being passed to udtrop() uninitialized, which is currently ok as it is not used, however lets assume that udtrop() might also wish to use the baseline and initialize it.
=> rtkpos udstate: compute baseline for update of tropospheric parameters

src/options.c
Four frequencies are an option, but the common builds appear to define NFREQ to 3. Some of the data structure are defined as size NFREQ and the code iterates over them using the supplied optional number of frequencies which might be greater. So here is a suggestion to limit the optional number of frequencies to the build NFREQ, and to emit a warning if this does occur. It is possible that I am misunderstanding the intention for 4 frequencies.
=> options number of freq: limit for build NFREQ

src/convrnx.c
Noticed one missing guard. Other uses seem guarded.
=> convrnx: guard against RINEX option comments overflow

src/stream.c
If there is a user name component but not a password component then the nul char was written to pointer NULL.
=> stream decodeftppath: avoid null pointer defreference

src/rtkpos.c
It is possible that there are no valid satellites and in this case an OOB read with potential unintended behaviour was occurring.
=> rtkpos ddidx: guard no good satellites being found

src/gis.c
The skiping of a record was using the same 'i' index as the outer loop. Use a separate index.
=> gis_read_record: avoid loop index corruption

app/qtapp/rtknavi_qt/navimain.cpp
There were paths in which the cmd and cmd_periodic strings were not being initialized and these were being passed to rtksvrstart().
Same issue on the demo5 branch.
=> rtknavi_qt serverStart: initialize cmd strings emptry

src/streamsvr.c
Getting an OOB read as strsvrstart() wants 8 options but strsetopt() was only allocating 5.
=> strsvrstart: strsetopt() wants 8 options

app/consapp/convbin/convbin.c, app/consapp/pos2kml/pos2kml.c, app/consapp/rnx2rtkp/rnx2rtkp.c, app/consapp/rtkrcv/rtkrcv.c, app/consapp/str2str/str2str.c
Use the standard EXIT_FAILURE as the command failure exit code rather than -1 (255) or -2 (254).
Also the rnx2rtkp command was returning the codes from the function postpos(), and now just return EXIT_FAILURE for anything but success.
This would change the exit codes, might break some script that checked for a specific code rather than just success or not-success. But the current negative codes will not pass through to the shell as is, they will be truncated to an unsigned 8 bit value. rnx2rtkp seems the only affected command in practice. Could just ignore this suggestion, it is just a standardisation suggestion.
=> consapp: normalize exit codes

src/convgpx.c, src/convkml.c
These were leaking the solution buffer.
=> convgpx, convkml: free the solution buffer when done.

src/stream.c
to fix issue #66, this pull request will add leading slash to source connection and allow connection contain slash. the old ntrip client can still connect to new server without add leading slash, but old ntrip caster can not deal with connection with leading slash.
=> add and allow leading slash of ntrip source request

src/rinex.c
current version writes v3 event strings to v2 files
=> rinex_v2_event_format_fix

app/qtapp/appcmn_qt/navi_post_opt.cpp, app/qtapp/appcmn_qt/navi_post_opt.ui, app/qtapp/rtkpost_qt/postopt.cpp
* rover and reference position types were reversed in the ini file
* solstatic option was feeding from the gui solution format
* the solution format was always disabled, stuck at 0.
* connect up the process options for the SNR and receiver error
* enable 'solution static' label when this respective input is enabled
* add 'combined - no phase reset' as a solution option
=> qt_gui misc settings fixes

lib/iers/src/vmf1_ht.f
Fixes the following compilation warnings:
../src/vmf1_ht.f: In function ‘vmf1_ht_’:
../src/vmf1_ht.f:127:132: warning: ‘cw’ is used uninitialized [-Wuninitialized]
127 |       TOPCON = (1D0 + AW/(1D0 + BW/(1D0 + CW)))
|                                                                                                                                    ^
../src/vmf1_ht.f:97:44: note: ‘cw’ was declared here
97 |      .                 GAMMA, TOPCON, BW, CW, PI, TWOPI, A_HT, B_HT,
|                                            ^
../src/vmf1_ht.f:127:132: warning: ‘bw’ is used uninitialized [-Wuninitialized]
127 |       TOPCON = (1D0 + AW/(1D0 + BW/(1D0 + CW)))
|                                                                                                                                    ^ …
=> Fix VMF1_HT subroutine

app/consapp/rtkrcv/rtkrcv.c
The printf format for the leap seconds was %d but the value is a double.
=> rtkrcv prnavidata: leap seconds is a double

src/rcv/ublox.c
Give the respective variables a default value before attempting to parse the value, just in case the parsing fails.
Also corrected a comment for the option MAX_STD_CP, assuming not MAX_STD_CP
=> ublox: default the MAX_STD_CP and STD_SLIP values before parsing

app/qtapp/rtknavi_qt/naviopt.cpp, app/winapp/rtknavi/naviopt.cpp
The 'stat' output option is supported in the interface, so add it to the SOLOPT option string. This allows this option to be written and read back as a string in a config file.
=> rtknavi: Add the 'stat' solution option comment

app/qtapp/rtkplot_qt/plotinfo.cpp
Windows app does not have this issue.
=> rtkplot_qt Plot::UpdateObsType: correct arg to code2obs()

app/qtapp/rtknavi_qt/mondlg.cpp
The solution stats can be output now and without entry there was an oob access. Just add them all.
=> Qt gui showStream: add all out formats

app/qtapp/rtknavi_qt/mondlg.cpp
The GUI has an option for showing the 'combined' input buffers, but this was not implemented here causing OOB reads.
=> Qt gui showBuffers: implement the 'combined' input option

src/postpos.c
It is not modified, and the copy was not being used consistently.
Perhaps also clean this up for clarity.
=> postpos execses: don't need to copy the sopt

app/consapp/convbin/convbin.c, app/qtapp/rtkconv_qt/convmain.cpp, app/winapp/rtkconv/convmain.cpp, src/convrnx.c, src/rinex.c, src/rtklib.h
Noted an OOB access in the rnxopt mask, the constant 64 length is less than MAXCODE. This will also be needed for the qt_gui branch where this was first noted.
While checking further, added defines for the particular system index used in the rinex code. The convbin app had not been updated to iterate over all 7 systems. Have not checked the other front ends or made uses of these defines there, but they appear to bake in 7 systems.
Seems odd having a separate index sequence just for the rinex code, but this is a least a step towards cleaning that up. But it some baked in constants have been missed then it will break something to change the order. So suggest revisiting such a change as a later step.
=> Rinex mask defs

src/stream.c
ntrip->buff being terminated with '0' rather than '\0'
=> stream ntrip: correct some buffer nul terminations

app/qtapp/appcmn_qt/navi_post_opt.cpp
These are the pos2-rejionno and pos2-rejcode options respectively, and they were mixed up in places.
=> Qt gui options: correct ordering of maxinno phase vs code

app/qtapp/rtknavi_qt/navimain.cpp
Remove redundant computation of the stream type. It is computed just above with guards.
Correcting a prior patch to this same code, perhaps my merge error sorry.
=> Qt gui rtknavi_qt: showOptionsDialog stream guard

app/qtapp/rtknavi_qt/mondlg.cpp
There are a few more paths that allow the 'combined' input stream option but do not support this: RTCM, RTCM SSR, reference station.
For now guard against this unsupported option by using only the rover input stream in these paths.
=> Qt gui monitor: guard paths using the 'combined' input stream

app/consapp/convbin/convbin.c, app/consapp/pos2kml/pos2kml.c, app/consapp/rnx2rtkp/rnx2rtkp.c, app/consapp/rtkrcv/rtkrcv.c, app/consapp/str2str/str2str.c
Requested here https://github.com/rtklibexplorer/RTKLIB/issues/332
The -v argument is already taken in some apps, so use --version.
Quick suggestion for the output, could do it differently.
=> console apps: add a --version command line option

app/qtapp/strsvr_qt/mondlg.cpp, app/winapp/strsvr/mondlg.cpp
If not zero filled then on a format change either free_rtcm or free_raw will be called with a garbage struct and in turn free() will be called with garbage.
=> strsvr: zero the rtcm and raw structs

app/qtapp/rtknavi_qt/navimain.cpp
Rather than just testing for any nav->eph, iterate over the actual number of nav->eph elements. This also add the ability to save all sets where there are more than the 2 sets currently saved.
=> Qt gui saveNavigation: modify the guard, use the number of elements

app/qtapp/appcmn_qt/navi_post_opt.cpp
Looks like the reference position tips were not updated when their order was changed.
Getting the reference position from RTCM should be enabled for rtknavi.
=> Qt gui reference position: fix tips order; enable RTCM for rtknavi

app/qtapp/rtknavi_qt/navimain.cpp
The code checks for a change in the monitor port and closes the old port and should be opening then new port.
=> Qt gui: correct opening of the monitor port

app/qtapp/appcmn_qt/tcpoptdlg.cpp
This is https://github.com/rtklibexplorer/RTKLIB/pull/303 rebased cleanly to demo5. Sorry if this is an unwelcome dup but it was closed without comment and there are issues here, so please just close it again if not interested.
Follow the logic in src/stream.c decodetcppath() to be consistent.
Update getPath() to only return those components available. It no longer tacks on a ':' separator for the STR component is there is none, or other unnecessary separators.
There might still be further issues with the presentation of the STR component for ntrip servers and casters.
=> Qt gui setPath: rework, correct

app/qtapp/rtknavi_qt/mondlg.cpp
setNavigationGPS() and showNavigationsGPS() were using different columns widths for SYS_SBS and STS_IRN, both also under the 'GPS' paths, so make these consistent.
=> rtknav_qt setNavigationGPS: keep column widths consistent with output

app/qtapp/rtknavi_qt/mondlg.cpp
The eph off need only be multiplied by the number of sats in each set once, and there can be more that two sets, the UI supports 4 sets and at most 4 sets are currently used in the library, and the code already guards against the offset begin OOB unless there was an issue with negative indexes.
See for example the current guard and use:
```
if (i + off * MAXSAT < rtksvr->nav.n)
eph[i] = rtksvr->nav.eph[i + off * MAXSAT];
```
=> rtknavi_qt mondlg: show nav offset is already guarded

src/rtkpos.c
Looks trivial and pointless, but it actually helps the compiler, helps code analysis reason about the code, and some warnings go away.
=> detslp_dop: hoist use of rtk->opt.nf

src/tides.c
Avoiding undefined behaviour by the caller in this case.
=> tide_pl: zero the output to dr[] on error

src/stream.c
The MacOS code recognised high unsupported baud rates and would then index oob into bs[] for these. Use a smaller set of recognised baud rates for MacOS.
=> stream openserial: avoid oob on MacOS for high baud rates

src/stream.c
The code was checking the basic authentication without also checking for the line termination, so it would match and accept a user plus password longer than expected so long as the prefix matched.
=> stream rsp_ntripc: check the basic authentication length

app/consapp/rtkrcv/rtkrcv.c, app/consapp/str2str/str2str.c, app/qtapp/strsvr_qt/svrmain.cpp, app/qtapp/strsvr_qt/svrmain.h, src/stream.c
stream.c: fix UDP trace format, was passing an int for a string pointer.
rtkrcv: correct the stream types array of strings; can add 'UDP client' as an output option.
str2str: add 'UDP client' as a stream output option.
QT str2str: correct the size of the paths[] array, there are 7 paths not 4, correcting an OOB access. Save and load all 7 path options to the ini file. Correct an outputTypes[] array which was missing an entry for UDP client causing an OOB for STR_FILE. Correct an index into the paths for the input options, the UDP input option is index 4.
=> misc udp stream fixes

app/consapp/rtkrcv/rtkrcv.c, app/consapp/str2str/str2str.c
Adds the --deamon option. The standard output and error are written to a new log file with this option. For rtkrcv also allow telnet consoles in general.
Not implemented for Windows, it will just use no console but not detach from the console.
This is a feature addition, with running in the background in mind, for example from a OS startup script, or when wish it to not exit when logging out.
For rtkrcv it could usefully be used with the -s option to startup RTK, but can also be started from a telnet console.
=> str2str, rtkrcv: add support to detach from the console

src/stream.c
otherwise this breaks when the write pointer is index 0.
noted in https://github.com/tomojitakasu/RTKLIB/pull/519
=> readmembuf: wrap around before comparing to the write pointer

app/consapp/rtkrcv/rtkrcv.c
Add a command line argument '-exec' to enable to feature.
Suggestion to disable the rtkrcv command shell feature by default. A telnet session over an insecure connection, with a default password 'admin', that can execute shell commands might catch someone out.
Perhaps people would want to give the argument another name.
=> rtkrcv: remove the shell command execution

src/convrnx.c
Both convobs and convsbs were omitting data that was within the time tolerance or later than the previous latest data time. This was intended to omit some duplicate data. At least for the SBAS data this heuristic was too strict as multiple messages typically occur with the same time and messages and ephemeris were being omitted.
Relax the test to now keep data within the time tolerance.
=> convrnx: relax the test for duplicate data

src/rcvraw.c
The results from getbitu() were being assigned or compared to signed integers. This quietens some warnings.
=> rcvraw decode_frame_alm: use uint32_t as appropriate

app/consapp/rtkrcv/rtkrcv.c, src/rtklib.h, src/rtkpos.c, src/rtksvr.c
The rtkrcv command was not copying the system output options to both of the output stream options, so the second streams always used the initialization options.
Move the output of the stats residuals from outsolstat() to rtkoutstat(), which allows the residuals to be output for the rtksvr output streams when the out-outstat is set to 'residuals'. A new argument is added to rtkoutstat() for the output level.
=> rtksrv: have stats out streams respect the stats level

app/consapp/rnx2rtkp/rnx2rtkp.c, app/consapp/rtkrcv/rtkrcv.c, app/consapp/str2str/str2str.c, app/qtapp/rtkget_qt/getmain.cpp, app/qtapp/rtknavi_qt/navimain.cpp, app/qtapp/rtkplot_qt/plotdata.cpp, app/qtapp/rtkpost_qt/postmain.cpp, app/qtapp/strsvr_qt/svrmain.cpp, app/winapp/rtkget/getmain.cpp, app/winapp/rtknavi/navimain.cpp, app/winapp/rtkplot/plotdata.cpp, app/winapp/rtkpost/postmain.cpp, app/winapp/strsvr/svrmain.cpp, src/convgpx.c, src/convkml.c, src/download.c, src/postpos.c, src/rtklib.h, src/rtksvr.c, src/solution.c, src/streamsvr.c
For the rtklib interface functions, declare char pointer arguments as 'const char ...' when the function does not modify the data. Many were already declared.
Some follow on patches are also included for some of the callees for consistency, and some of the caller arguments needed type casts.
=> rtklib interface const char

src/postpos.c, src/solution.c
outrpos() was using the option separator string raw, without interpreting as elsewhere through opt2sep(), and this made it incompatible with decode_refpos()
decode_soltime() can also use opt2sep() rather than repeating the same logic.
=> postpos outrpos: use the same interpretation of the opt sep as elsewhere

src/rtkcmn.c
My mistake. https://github.com/rtklibexplorer/RTKLIB/issues/412
=> ionppp: receiver position is in meters

app/consapp/convbin/convbin.c, app/consapp/str2str/str2str.c, app/qtapp/rtkconv_qt/convmain.cpp, app/winapp/rtkconv/convmain.cpp, src/rcv/unicore.c, src/rcvraw.c, src/rtklib.h
Added support for binary data output from Unicore receivers. Tested with data from UM980, UM981 and UM982 receivers.
The following messages are supported:
- OBSVMB
- GPSEPHB
- GLOEPHB
- BDSEPHB
- GALEPHB
- QZSSEPHB
- IRNSSEPHB
The Unicore parser is tested with CONVBIN and can convert Unicore data files to RINEX.
The file extension "unc" is used for Unicore data. This is non-standard and can be changed.
=> Added Unicore binary data decoder

app/consapp/rnx2rtkp/rnx2rtkp.c, app/consapp/rtkrcv/rtkrcv.c, app/qtapp/appcmn_qt/navi_post_opt.cpp, app/qtapp/appcmn_qt/navi_post_opt.ui, app/winapp/rtknavi/navimain.cpp, app/winapp/rtknavi/naviopt.cpp, app/winapp/rtkpost/postmain.cpp, app/winapp/rtkpost/postopt.cpp, src/options.c, src/rtklib.h
This patch have been dropped at the big Qt gui merge. This was largely for the gui, to allow the position inputs to be saved and load to config files in the same format presented in the GUI.
Add separate position option implementation states for llh and xyz position types. The implementation of the antenna types was already consistent with the configuration options for the antenna types, but the implementation state in refpos and rovpos dropped the distinction between llh and xyz position formats and so lost the distinction when converting back to the configuation option.
Now the rovpos and refpos use the same set of states as the antenna types, including llh and xyz position types, although the positions stored in ru and bu are still always in xyz format.
This simplifies the option …
=> Rework the implementation of the position options

src/sbas.c
The subtype7 messages have at most data for the first 51 masked satellites, so guard this as had already been done for subtype6 messages.
=> sbas subtype7: guard the number of satellites

src/rcv/septentrio.c
Storing the gtime into the subframe buffer was causing unaligned access issues. This PR stores the integer seconds which is adequate here and uses memcpy.
The raw time is stored in the subframe buffer, beyond the data, and used to invalidate the buffer. Store the time in seconds, truncated to 32 bits, and use memcpy to read and write this to the buffer.
=> Septentrio GLO raw canav: avoid subframe time unaligned access

src/rcv/septentrio.c, src/rcv/ublox.c, src/rinex.c, src/rtklib.h
* Fixes for the SNR decoding.
* Fixes for the doppler decoding.
* Fixes for the GLONASS fcn indexes. The conventions differ in various RTKLib structures. Needed in part to fix the doppler decoding.
* Remove the constraint that the Lstd and Pstd values be limited to 9, rather apply this limit on RINEX output, to benefit from the wider range when using a raw input.
* Add a -RCVSTDS receiver option for the Septentrio to make this optional, as for the ublox.
=> septentrio: misc fixes, snr, doppler, glonass fcn, add RCVSTDS opt

app/qtapp/rtkplot_qt/plotcmn.cpp, app/winapp/rtkplot/plotcmn.cpp
and for rtkplot_qt correct the legend color.
Some of the lower end receiver data sets have a lot of signals now, and the extended observations were not being counted.
The Qt rtkplot legend color was not matching the plot color.
=> rtkplot: count all observation frequencies

src/rcv/septentrio.c
Time was loaded from incorrect offset. Compute in double.
=> septentrio sbslongcorrh: correct time decoding

src/rcv/septentrio.c
Saw this is a dataset, might as well as a switch case for it.
=> septentrio: add case for ID_GEOALM, not yet implemented

src/rcv/septentrio.c
decode_glonav: correct svh. Only a binary health bit is wanted for the GLONASS svh.
decode_galnav: correct code and health, convert to RINEX format.
decode_meas3Doppler, decode_meas3CN: correct loop oob
meas3_sig2idx: use MEAS3_SIG_MAX
decode_gpsrawcnav: add partial implementation
decode_galrawfnav: correct code
decode_galrawinav: correct code
decode_navicraw: enable
decode_naviclnav: enable
decode_cmpnav: correct times
decode_qzssnav: correct, enable
Set the eph.set even if it is zero, just to be explicit.
=> septentrio: misc fixes

app/qtapp/rtknavi_qt/navimain.cpp, app/qtapp/rtknavi_qt/navimain.h
The rtksvr structure size is approaching the default stack size on Linux, so move it off the stack.
=> rtknavi_qt: allocate the rtksvr structure off the stack

app/qtapp/rtknavi_qt/mondlg.cpp
to avoid excessive abbreviation.
=> rtknavi_qt mondlg: expand obs code widths

src/rinex.c
Spotted this code that does not appear correct. The RINEX 3 spec details the code bits as follows so the current code checking bit 9 for a f/nav set seems wrong.
> Bit 0 set: I/NAV E1-B
> Bit 1 set: F/NAV E5a-I
> Bit 2 set: I/NAV E5b-I
> Bits 0 and 2 : Both can be set if the navigation messages were merged,
> however, bits 0-2 cannot all be set, as the I/NAV and F/NAV messages contain different information
> Bit 3 reserved for Galileo internal use
> Bit 4 reserved for Galileo internal use
> Bit 8 set: af0-af2, Toc, SISA are for E5a,E1
> Bit 9 set: af0-af2, Toc, SISA are for E5b,E1
> Bits 8-9 : exclusive (only one bit can be set)
Set 0 is used for I/NAV and set 1 for F/NAV. The ephemeris structure code slot has bit 8 set for E5a,E1 or bit 9 set for E5b,E1. F/NAV is for channel E5a-I, not …
=> RINEX input_rnxctr: correct the ephemeris set for GAL

app/consapp/convbin/convbin.c, src/convrnx.c, src/rtklib.h
This helped compare rtklib output rinex observation files vs other. Other rinex files could also be filtered through convbin to have the same ordering before a text comparison. Is there a better tool to compare rinex files, something that can actually note the numerical differences and ignore lsb diffs?
Using the RTKLib satellite index.
Adds -sortsats to convbin
=> convrnx: add option to sort observation data by satellite index

src/rcv/crescent.c, src/rcv/javad.c, src/rcv/novatel.c, src/rcv/septentrio.c, src/rcv/skytraq.c, src/rcv/ublox.c, src/rcvraw.c, src/rinex.c, src/rtcm3.c, src/rtcm3e.c, src/rtklib.h
Notice this issue when comparing the septentrio nav output to that expected. The fit time was typically being output as zero in the RINEX nav, which was okay, but it could be better and the internal usage was not consistent.
Add a sys argument to decode_frame so that it can specialise for QZSS where the interpretation of the fit bit differs from GPS.
Rework some usage of the eph.fit which is defined in RTKLib to be in hours, so the decoded fit time, not the binary bit. It was not being consistently set. Now it is set to 4hrs for GPS when appropriate, and for now to 6hr when over 4hrs (it could be better decoded). For QZSS it is set to 2hrs when appropriate and to 4hrs when over 2hrs; QZSS appears to only use 2hr.
The fit time is not currently used by RTKLib, just past through.
=> eph.fit: improve handling, QZSS

src/rcv/binex.c
The code was returning -1 for these errors in some places and 0 in others, a returning -1 appears appropriate for these errors so just being consistent.
=> binex: correct some error return codes

app/qtapp/rtkplot_qt/plotdraw.cpp
The residuals can be zero and valid, a reference signal.
=> rtkplot_qt: show residuals even when zero

src/rcv/unicore.c
Corrected the header length byte offset in `input_unicore`.
I've tested this with my UM980 and looks good.
=> Unicore: Fix message length in input_unicore. Fixes #446

src/rtkcmn.c, src/rtklib.h
=> Add codes L6D and L6P for BDS B3A, and NavIC L1

app/consapp/convbin/convbin.c
Might as well handle all signals by default, to avoid having to track down missing signals to this setting. This is effectively a mask so does not need to match NFREQ and NEXOBS.
=> convbin: change the default frequencies to all

app/qtapp/rtkconv_qt/convmain.cpp, app/winapp/rtkconv/convmain.cpp
Looks like merge issues. Need to correct the mask length to cover all the codes. Redundant copy on win app. Avoid some more baked in constants.
=> convmain: misc cleanup constant use

src/rtcm3e.c
The MAXOBS was being used, where 31 is the maximum number of satellites for these messages.
This limit was not being enforced when emitting the data, just in the header value.
This lead to an invalid RTCM data stream when there were over 31 satellites.
=> rtcm3e msgs 1001-1004, 1009-1012: correct max satellites limit

src/rcv/unicore.c
Prior patch used the wrong destination.
=> unicore: fix observation standard deviation recording

src/rtcm3.c
Received some clarification on the GLONASS signals https://github.com/tomojitakasu/PocketSDR/issues/28 and seems these are tentative, so propose following PocketSDR. Also adding more tentative signals for BeiDou from PocketSDR which but not yet the duplicate allocations for 1D 1P 1X https://github.com/tomojitakasu/PocketSDR/issues/29
The GLONASS signals extensions are apparently tentative, so adopt the PocketSDR tentative assignments.
Try to clarify the tentative signal assignments in comments.
Add tentative signal assignments for BeiDou 6D, 6P, 6Z, 8D, 8P, 8X from PocketSDR, missed.
Add tentative signal assignments for QZSS 1E, 1Z, 1B, 6E, 6Z, 5D, 5P, 5Z from PocketSDR, missed.
=> rtcm3: further sync with PocketSDR

src/rtkcmn.c
There needs to at least be an entry in codepris for signals, even if the appropriate ordering is not settled, and missed these in the last attempt.
=> rtkcmd codepris: add QZSS 1B 1E, BDS 1S 1L 1Z

util/rnx2rtcm/makefile, util/rnx2rtcm/rnx2rtcm.c
This utility has been useful for RTCM testing, to generate RTCM from a RINEX file, to test the RTCM encoder and decoder.
Pack observations across multiple messages if necessary.
Add -opt for RTCM, and -rnxopt for RINEX, command line arguments.
Use the RINEX GONASS fcn.
Update the supported nav messages.
=> rnx2rtcm: update

src/rtkcmn.c
The Galileo I/NAV and F/NAV eph have some differences and should both be retained even if they have the same toe and iode.
Also include I/NAV vs F/NAV distinction in the sort ordering function.
=> uniqeph: keep Galileo I/NAV and F/NAV separate

src/rtksvr.c
4 sets are being allocated, but nav.n was initialized for just 2
=> rtksvr: correct initialization of nav.n

src/postpos.c
In the case of both a start and end time an over allocation to ifile[] was occurring, memory not free. Need only 'n' elements.
=> postpos: avoid over allocation in ifile[]

src/rtkpos.c, src/rtksvr.c
With more frequencies, the number of $SAT lines increases and the static buffer was overflowing.
=> rtkpos outsolstat: increase stat output buffer

src/rtklib.h, src/rtkpos.c
This addresses an issue noted with https://github.com/rtklibexplorer/RTKLIB/pull/502 and should unblock that path.
The code is currently limited to one bias per satellite and pair of receiver signals. If one of these signals changes then flag a slip to have the bias reinitialized. Otherwise such changes can throw off the solution.
The expected observation code is initialized when first seen, and typically does not change, but the processing is now robust to signal changes. This initialization accepts different signals at the same frequency index across a system, but just one signal at a time for a particular satellite and receiver per frequency index.
=> rtkpos: detect code changes per frequency index

src/ppp.c
The var[] can have an entry for each frequency, and was overflowing.
=> ppp_res: the var[] array needs room for all frequencies

app/consapp/rnx2rtkp/rnx2rtkp.c
to allow tracing output before it is otherwise initialize for each rover.
=> rnx2rtkp: initialize tracing

src/postpos.c
The iobsr index can be out of range of the obs data, beyond the end or the start, such as when there is only one receiver. inputobs() was indexing into the data using the out of range iobsr index.
Remove a redundant call to nextobsf() in the case that an immediate prior call returned zero.
Small performance improvement for nextobsf() and nextobsb(). Avoid comparing the obs times if an obs with a different rcv is found first.
=> postpos inputobs: guard against iobsr being out of range

app/consapp/rtkrcv/rtkrcv.c
Was leaving the frequency value blank for 5 or 6 freqs, might as well print some indication.
=> rtkrcv prstatus: fill in the output for 5 to 7 freqs

src/rcv/novatel.c
Bynav M2 series low-cost receivers use Novatel binary protocol.
This patch add some little code modification to convert raw data to RINEX.
=> Add Bynav M2 series support to novatel.c

src/rtkcmn.c
The G3 and G1a and G2a signals have a common frequency between satellites so their frequency determination does not depend on the fcn and so do not give up on these if there is no fcn data.
=> sat2freq GLO: only require the fcn for G1 and G2

src/rtcm3.c
The PocketSDR has a duplicate set of BDS 1D, 1P, 1X RTCM3 codes, so that duplicate was left out in the prior patch, but noticed that 1S 1L and  1Z are missing, so now guess that it was a typo and that 1S 1L 1Z are intended.
=> rtcm3: add tentative BDS 1S 1L 1Z RTCM3 codes

src/postpos.c
readpreceph() and freepreceph() need not allocate and free the sbas ephemeris as this is done by readobsnav() and freeobsnav(), and readobsnav() was overwriting the data structures setup by readpreceph() without freeing them leading a loss of memory.
=> postpos readpreceph: omit alloc and free of the sbas ephemeris

app/qtapp/appcmn_qt/graph.cpp
The intermediate calculations have been noted to overflow the int32_t, so use an int64_t here.
=> qtapp clipPoint: use intermediate int64_t to avoid overflow

app/qtapp/rtkconv_qt/codeopt.cpp, app/qtapp/rtkconv_qt/codeopt.ui
Off by one issue with L1S and L1L, was including L1E and missing L1S, and the respective mask bits were off.
=> qtapp codeopt: correct C07/L1S and C08/L1L selection

app/qtapp/appcmn_qt/navi_post_opt.cpp
avoids an OOB read setting up the tool tips when NFREQ > 4.
=> qtapp navi-post-opt: tool tips for 5+ frequencies

src/ephemeris.c
Compared to eph2clk and geph2clk, it does not look correct. I don't have the documentation to double check, but this looks a lot more plausible.
=> seph2clk: correct recursive expansion

src/rtkpos.c
The heuristics in manage_amb_LAMBDA() select a rolling satellite to test for exclusion, to see if it improves the ambiguity ratio. This was intending to note the sats used for AR, but was also iterating over the frequencies and noting sat/freq used for AR, but the array to hold the sat mapping was only large enough for the sats, not sats*freqs, leading to OOB access when there were many observations and frequencies. It was rolling over this combination, not as intended. Further it was sensitive to changes in the set of sats used for AR, the rolling point could jump around, jump back, and not progress smoothly thought the set of sats. Rework to address these issues, to roll through that sats smoothly.
Could have addressed the OOB along by increasing arsats[]. Guessing that the bumbling …
=> rtkpos: rework the rolling exclusion of satellites

app/consapp/str2str/str2str.c
MAXSTR was not the appropriate definition of the buffer size here as it is the number of streams which is distinct from the command line read chunk size. Use a read chuck size of 81 characters.
Pass in the target cmd size, rather than depending on MAXRCVCMD.
Exit as soon as the target is full, rather than filling with smaller later chucks, and emit a warning on overflow.
=> str2str readcmd: avoid constant sizes

src/rcv/ublox.c
ID of ubx message is full 8bit.
It makes debugging easier.
=> corrected printing out ID of raw ubx message

src/rtkcmn.c
Noted GFZ ERP files use UT1-TAI and were not read correctly.
The UT1-TAI offset is included in the IGS format, and products using this offset are being produced. Canonicalised these offsets to UT1-UTC for consistent internal use.
Also detect the IGS format as having 'VERSION 2' in the first line, and distinguish between header and data lines, and support concatenated files that include the version and header lines.
=> readerp: support IGS UT1-TAI offsets

src/rtksvr.c
rather than filling these with ne and nc respectively.
Was not a issue, but just inconsistent.
=> rtksvr decodefile: copy nemax and ncmax

app/consapp/rtkrcv/rtkrcv.c
and coerce to an unsigned long.
=> rtkrcv: print the rtk server thread as hex number

src/rtkcmn.c, src/rtklib.h
Add a THREADLOCAL definition that maps to _Thread_local for C11, __thread for gcc, and __declspec(__thread) for MSC.
Use this to make the eci2ecef() cache thread safe.
Testing on linux. If people could test this on other platforms, and if there is a workable thread local declaration, then this could be useful in a few other places. Worst case the definition could be empty for platforms without thread local storage declarations and then these uses would remain not thread safe for now on these platforms. The MSC declaration is based on https://learn.microsoft.com/en-us/cpp/cpp/thread?view=msvc-170 For C11 _Thread_local appears to be usable, but RTKLIB currently targets C99 so this also maps to GCC amd MSC extensions.
=> eci2ecef: thread safety, add THREADLOCAL

src/rcv/novatel.c
Galileo CODE_L1B is not suitable for processing.
This modification from L1B to L1C allow to run processing on this observation.
=> Bynav Galileo code E1B to E1BC modification

src/rtklib.h, src/rtkpos.c
Static data is not thread safe. Use stack allocated data for all the scratch data, and move the remaining static data into the rtk_t structure. This also allows it to be reinitialized.
Should be not change to the function, this is just to move the data. Might avoid a startup glitch on restart now.
=> rtkpos intpres: move static data to rtk_t

src/rtkcmn.c
Fix a merge issue with the sofa changes. The functions epv00 and moon98 are defined in `src/sofa.c` and need only be declared in rtkcm.c. If there is a compilation issue with these not being defined then the build definitions need to be updated to also include src/sofa.c, and hopefully someone can address that for the windows builds if that was the issue.
=> sunmoonpos_eci: declare epv00 and moon98 prototypes

app/qtapp/rtkplot_qt/plotmain.cpp
to avoid a crash when trying to free garbage
=> rtkplot-qt: initialize ionosphere

app/qtapp/appcmn_qt/navi_post_opt.cpp, app/qtapp/appcmn_qt/navi_post_opt.ui
The first combo box is for selecting an ambiguity resolution strategy, which is applied for all GNSSs. The other two combo boxes allow special settings for GLONASS and Beidou. The first combo box is renamed to reflect that the strategy applies to all GNSSs.
=> Rename the combo box for ambiguity resolution

src/sbas.c
not thread safe, and unlikely to be a bottleneck now.
=> sbstropcorr: thread safe cache

src/trace.c
This minor fix prevents accidentally closing stderr, see also the traceclose function in line 49.
=> do not close stderr by accident

src/postpos.c
For the case in which there is a start and end time and a unit period, the number of input files can grow in` reppaths()` and this function was being allowed to use up to `MAXINFILE `files so these all need to be allocated and freed in this code path.
Building on https://github.com/rtklibexplorer/RTKLIB/pull/609 but allocate all `MAXINFILE `elements to `infile[]` in this code path which is around 1M of memory usage.
=> postpos: when processing unit periods alloc for all infiles

src/postpos.c
just to report a failure and handle it a little more gracefully.
=> postpos procpos: catch malloc failure

src/rtcm3.c
just to quieten a compiler warning of a loss of precision.
=> rtcm3 decode_ssr3: quieten compiler warning, loss of precision

src/rcv/unicore.c
rather than returning 1 which would indicate there have been observations.
This is an alternative for https://github.com/rtklibexplorer/RTKLIB/pull/528 where -1 is suggested to be returned in this case, however -1 appears to be for a error case and it is not clear that this raw message with zero observations is an error.  Also this includes only the update to unicore.c.
=> unicore decode_obsvmb: return 0 if no observations

src/rtklib.h, src/rtkpos.c, src/rtksvr.c, src/solution.c
Correct a further noted overflow in this buffer increasing it from 24576 to 32768, and clean up the usage of the buffer size.
A further overflow was noted, but with over 40 satellites and with support for 5+ frequencies enabled.
This definition is used for a buffer size for solution status messages and as the number of satellites and frequencies has increased this buffer has needed to grow. There is a $SAT solution status line for each satellite frequency.
In places this buffer size had been increased as overflows were noted, but not consistently, so update the definition and correct the references.
MAXSOLLEN - add a new definition for the solution status line buffer length. There were cases in which the MAXSOLMSG buffer size was being used for a single line buffer which was excessive, …
=> MAXSOLMSG: increase to 32768, to correct an overflow

src/rtksvr.c
For the newly added rtcm rewind-and-retry on error feature, reference the respective rtcm object for each stream, rather than always the first.
=> rtksvr rtcm3: reference the respective rtcm object

src/postpos.c
Noticed a solution was a little off at the start and end of an odd time span that did not align with the base period of 30 seconds, and including a base observation before and after the rover time span helped.
=> postpos: expand base obs time span for interpolation

app/qtapp/rtkconv_qt/convmain.cpp
Use the start time (if enabled) for conversion of streaming formats (like RTCM3)  rather than current time. Reverts back to old functionality when `Time Start` is not specified.
=> Improve start time settings for streaming format conversions

app/qtapp/CMakeLists.txt, app/qtapp/rtkconv_qt/rtklib_zh_CN.ts, app/qtapp/rtkget_qt/rtklib_zh_CN.ts, app/qtapp/rtklaunch_qt/rtklib_zh_CN.ts, app/qtapp/rtknavi_qt/rtklib_zh_CN.ts, app/qtapp/rtkplot_qt/rtklib_zh_CN.ts, app/qtapp/rtkpost_qt/rtklib_zh_CN.ts, app/qtapp/srctblbrows_qt/rtklib_zh_CN.ts, app/qtapp/strsvr_qt/rtklib_zh_CN.ts
I have added Chinese language support to demo5. When the user's system default language is set to Chinese, the build process will generate 8 localized versions of the Qt app in Chinese. Some screenshots of the localized app interface are shown below.
=> feat: Add Chinese localization

app/qtapp/rtknavi_qt/navimain.cpp
Was saving only 4 of 8 elements. Not consistent with the winapp.
=> rtknavi_qt save nav: write all the utc_gps data

app/consapp/convbin/convbin.c
This RTCM time is a rough time needed to determine the absolute time from the incomplete RTCM encoded time. This can be supplied by the '-tr' argument but this will often be start time. So if not supplied by this argument then use the supplied start or end time before falling back to using the file time because the file time can change if copied or processed.
=> convbin rtcm time: use the start or end time if supplied

src/rtcm2.c
Rebasing https://github.com/rtklibexplorer/RTKLIB/pull/471 which was entangled with other proposals. Guess this was not used as it was not complete, but might as well get it working.
The flushing of the observation data was broken, occurred only when not full, so once full it was stuck.
Implement the carrier-phase computation, when the pseudorange becomes available. It had been leaving the partial carrier-phase.
=> rtcm2: complete observation data decoding

src/rtcm3.c
The flushing of the observation data was broken, occurred only when not full, so once full it was stuck.
=> rtcm3: fix flushing of observation data

app/winapp/rtkconv/codeopt.cpp, app/winapp/rtkconv/codeopt.dfm, app/winapp/rtkconv/codeopt.h
Updates the codes to parallel the qt app.
GPS was missing code 1X. QZSS was missing codes 1B and 1E. NAVIC was missing codes 1D 1P 1X. BDS had unknown codes 1A 1N 6A, and was missing codes 1S 1L 1Z and 6D 6P 6Z.
=> winapp rtkconv codeopt: update codes

src/rcv/tersus.c
This PR implements the `decode_bd2ephemb` function in the tersus.c file. The function is designed to decode BD2 ephemeris messages, as specified in Chapter 9.16.3 BD2EPHEM of following handbook (in Chinese)
https://mdmobs.cpuniverse.cn/gitbook/02-%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97/Misc/gnss/unicorecomm/Unicore%20Reference%20Commands%20Manual%20For%20N2%20High%20Precison%20Products_V1_CH_R3.5.pdf
=> support tersus bd2ephemb

app/consapp/rtkrcv/rtkrcv.c, app/qtapp/rtknavi_qt/instrdlg.cpp, app/qtapp/rtknavi_qt/navimain.cpp, app/winapp/rtknavi/instrdlg.cpp, app/winapp/rtknavi/naviopt.cpp
rtkrcv was missing 'rinex' and 'clk'.
qt app was missing 'unicore' and had 'sbas' and 'nmea' for which there is no support.
win app was missing 'unicore', 'rinex' and 'clk'
gui apps: add 'CLK' as an input format as there is support for this in rtksrc.c
=> input format options: correct, and add CLK

app/qtapp/rtknavi_qt/navimain.cpp, app/winapp/rtknavi/navimain.cpp
rather than just changing its visibility as the output stream and log stream change methods test if the start button is enabled and were not operating when started.
=> rtknavi_qt: enable and disable the start button

app/qtapp/appcmn_qt/console.cpp, app/qtapp/appcmn_qt/console.ui, app/qtapp/rtknavi_qt/mondlg.cpp, app/qtapp/strsvr_qt/mondlg.cpp, app/winapp/appcmn/console.cpp, app/winapp/rtknavi/mondlg.cpp, app/winapp/strsvr/mondlg.cpp
A few functions use similar code to output stream ASCII or hex to a console. The code was adding linefeeds to wrap lines and then detecting these, and also leaving them which was noise in most cases. This reworks the code to avoid these trailing linefeeds.
rtknavi_qt was initializing the stream console output checkbox to 'HEX' but the initial output was ASCII.
TODO Noticed that the qt app uses a proportional font for this console output which does not present well for the HEX output and also some of the other output presents better in a mono-space font as used in the windows gui apps.
=> gui console output cleanup

app/consapp/rtkrcv/rtkrcv.c, app/qtapp/appcmn_qt/glofcndlg.cpp, app/qtapp/rtknavi_qt/mondlg.cpp, app/qtapp/rtkplot_qt/plotdata.cpp, app/qtapp/rtkplot_qt/plotmain.cpp, app/winapp/appcmn/glofcndlg.cpp, app/winapp/rtknavi/mondlg.cpp, app/winapp/rtkplot/plotdata.cpp, app/winapp/rtkplot/plotmain.cpp, src/postpos.c, src/rtksvr.c
to help avoid stack overflows. In particular the nav_t object and MAXOBJS multiples of the obsd_t objects.
Seeing stack overflows working on the windows rtknavi app, it might be just a 1M stack size, and this resolved it, but that was working with more than the default number of frequency indices and other extended data. Applied the same to the qt app.
=> Convert some larger stack allocations to heap allocations

.gitignore, app/consapp/.gitignore, bin/.gitignore, lib/.gitignore, test/utest/.gitignore
- Moved directory-specific ignore patterns from the root `.gitignore` to `.gitignore` files in `bin/`, `lib/`, `app/consapp/`, and `test/utest/`
- Improves clarity and maintainability of ignored files for each subdirectory
- Keeps the root `.gitignore` cleaner and more focused
=> Refactor .gitignore: Move directory-specific rules to subfolders

src/convrnx.c
which was not returning the expected difference and this caused some implementations of qsort to fail.
This caused the windows rtkconv to lockup when satellite sorting was enabled. It fixes my prior error here, but the linux glibc implementation of qsort must have been hardened to protect against this programming error and was working.
=> convrnx sort sats: fix the comparison function

src/postpos.c
just to be consistent with the other header values.
=> postpos: align header ref pos

app/qtapp/rtkplot_qt/plotcmn.cpp, app/qtapp/rtkplot_qt/plotdraw.cpp, app/qtapp/rtkplot_qt/plotinfo.cpp, app/qtapp/rtkplot_qt/plotmain.cpp, app/qtapp/rtkplot_qt/plotmain.h, app/winapp/rtkplot/plotcmn.cpp, app/winapp/rtkplot/plotdraw.cpp, app/winapp/rtkplot/plotinfo.cpp, app/winapp/rtkplot/plotmain.cpp, app/winapp/rtkplot/plotmain.h, src/solution.c
In part prompted by the discussion in https://github.com/rtklibexplorer/RTKLIB/discussions/712 This is for the Qt rtkplot, but can have a look at windows app support if this is considered useful.
The solution stat file has the satellites used in the solution and the satellite azimuth and elevation which is a usable input for these plots, and without loading the observation and navigation data. It also gives the data used in the solution. These are added as additional plots to the current observation data based sky and DOP plot which are still useful when examining this data and planning solutions.
=> rtkplot: add sky and DOP plots using the solution stat input

app/consapp/.gitignore, lib/.gitignore, test/utest/.gitignore
rather than using this as a 'gitconsider'.
The current .gitignore failed to include the directories in the app/consapp/ and perhaps there are other issues. Not an expert on gitignore but it would appear to have been intended to ignore the particular rather than to ignore all and then consider the particular.
=> gitignore: use positive logic

src/rcv/septentrio.c, src/rcv/ublox.c
For the GEO satellites nav subframe 5 the page number is a 7 bits rather than four and this is needed to find page 105.
=> Correct sept and ublox BDS CNAV UTC decoding

src/stream.c
e.g. /usr/bin/str2str -in ntrip://... -out tcpsvr://127.0.0.1:2200 ignores the given server address and always binds to the global interface. This patch fixes that behaviour and binds to given server address (or global interface when not specified).
=> don't ignore local server host address for tcp server

app/qtapp/appcmn_qt/glofcndlg.cpp
failed to update a ref to nav in prior patch, but the memset is not needed as calloc zero fills so just remove this code.
=> qtapp glofcndlg: correct zero fill of nav struct

.clang-format, app/consapp/convbin/convbin.c, app/consapp/str2str/str2str.c, app/qtapp/rtkplot_qt/plotmain.cpp, app/winapp/appcmn/graph.cpp, app/winapp/rtkconv/convmain.cpp, app/winapp/rtknavi/navimain.cpp, app/winapp/rtkplot/plotmain.cpp, app/winapp/strsvr/svrmain.cpp, src/convrnx.c, src/geoid.c, src/rcv/comnav.c, src/rcv/javad.c, src/rcv/nvs.c, src/rcv/rt17.c, src/rcv/septentrio.c, src/rcv/tersus.c, src/rcv/ublox.c, src/rinex.c, src/rtcm3.c, src/rtksvr.c, src/solution.c, src/stream.c, src/tle.c, test/utest/t_geoid.c, test/utest/t_tle.c, util/geniono/geniono.c, util/geniono/genstec.c, util/geniono/rcvdcb.c
In case a source code reformat is being considered with the transition to the new branch and naming, here is a proposal. 
There are just a few preparation patches to assist. Clang-format also reordered include files, and this caused an issue with one file on the windows app. Also code within `#if 0` was not reformatted, so use `#ifdef` , and code that was commented out was not reformatted so replacing that with `#ifdef`.
This does not include the actual reformat which would be a huge PR, but on linux the command line to reformat the code in a directory:
```
find . -name "*.cpp" |xargs clang-format -i
find . -name "*.c" |xargs clang-format -i
find . -name "*.h" |xargs clang-format -i
```
This proposes using the same format for all the code, but perhaps a variation could be considered for …
=> Clang format

src/postpos.c
procpos() can be called with fptm NULL, and in this case do not use fptm.
=> procpos: guard against fptm being NULL

src/convkml.c, src/convrnx.c, src/download.c, src/geoid.c, src/pntpos.c, src/postpos.c, src/ppp.c, src/ppp_ar.c, src/preceph.c, src/rcv/binex.c, src/rcv/javad.c, src/rcv/nvs.c, src/rcv/rt17.c, src/rcv/septentrio.c, src/rcv/unicore.c, src/rcvraw.c, src/rinex.c, src/rtcm2.c, src/rtcm3.c, src/rtcm3e.c, src/rtkcmn.c, src/rtkpos.c, src/sbas.c, src/solution.c, src/stream.c, src/streamsvr.c
Unused variable warnings are quietened by using (void)var.
Deals with issues raised in https://github.com/rtklibexplorer/RTKLIB/pull/732 but without commenting out code.
=> quieten misc compiler warnings
